version: 0.0
os: linux
hooks:
  Install:
    - location: scripts/install.sh
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3600
  ValidateService:
    - location: scripts/postconf.sh
      timeout: 3600
